# Generated by Django 5.2 on 2025-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlecture',
            name='speaker',
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='speaker_name',
            field=models.CharField(default='Unknown Speaker', max_length=255),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
