# Generated by Django 4.2.20 on 2025-05-06 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_guestlecture_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlecture',
            name='attendees',
            field=models.ManyToManyField(related_name='registered_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
